// ─── INFO MAPS: What each config does + which dashboards/stakeholders it affects ───
export const MODULE_INFO: Record<string, string> = {
  'Fee Configuration': 'This is where you set up your entire school fee structure. Define what fees you charge (tuition, transport, lab, etc.), how much each grade pays, which payment methods parents can use, and what happens when fees are overdue. Every fee receipt, parent payment screen, and accounts report pulls from these settings.|When parents open their fee portal, they see the fee heads and amounts you configure here. The Account Head uses these settings to collect fees, generate receipts, and run defaulter reports. The Principal sees fee analytics on their dashboard. If you change a fee head here, it updates everywhere automatically.',
  'Academic Configuration': 'Set up your school\'s academic backbone here \u2014 which subjects each grade studies, how many sections per class, house names for inter-house competitions, holidays, and term dates. If your school has a preschool wing, you can configure that too.|Teachers see their assigned subjects and class lists based on what you set here. The timetable module uses your subject list to build period schedules. Exam modules pull subject names for marks entry. Even the student admission form uses your grade and section data.',
  'HR & Payroll Configuration': 'Configure everything related to your staff \u2014 departments (Teaching, Admin, Accounts), designations (Teacher, Clerk, Peon), salary components (Basic, HRA, DA), and how often salary is processed. You can also set up staff attendance methods and onboarding checklists for new hires.|The HR Manager uses these settings daily for attendance, leave, and payroll. Teachers see their salary slips based on the components you define here. The Account Head processes payroll disbursement using your pay cycle settings.',
  'Transport Configuration': 'If your school runs buses, configure everything here \u2014 routes with stops and timings, vehicle details, driver assignments, GPS tracking, and how transport fees are calculated (flat rate, distance-based, or per-stop). Also set up student pickup verification rules for dismissal time.|Parents can track their child\'s bus in real-time using settings you enable here. The Transport Head manages daily operations, route changes, and driver schedules. Security guards use your pickup verification rules at the school gate.',
  'Attendance Configuration': 'Choose how attendance is marked in your school \u2014 biometric, RFID card tap, manual register, or mobile app. Set whether attendance is taken once daily, twice (morning/afternoon), or every period. Configure what happens when a student is absent \u2014 should parents get an instant SMS? After how many continuous absences should the Principal be alerted?|Teachers see the marking interface you configure here. Parents receive absence notifications based on your rules. The Principal\'s dashboard shows attendance trends from this data.',
  'Exams & Grading Configuration': 'Define your school\'s examination system \u2014 whether you use percentage marks, letter grades (A, B, C), CGPA, or competency-based assessment. Set grade boundaries (e.g., A1 = 91-100), exam types (Unit Test, Mid-Term, Final) with their weightage, and what your printed report card looks like.|Teachers enter marks using the grading system you set here. Students and parents see results, grades, and report cards in the format you choose. The Principal gets exam analytics based on your grade boundaries.',
  'Communication Configuration': 'Control who can message whom in your school. Can parents directly chat with teachers, or only view announcements? Can students message the Principal? Set up auto-created groups (like class-wise parent groups), file sharing limits, and pre-built message templates for common notifications.|Every user\'s chat experience depends on these settings. Parents see messaging options based on your permission matrix. Teachers get auto-created class groups. The school admin can send broadcast messages using your templates.',
  'Timetable & Bell Schedule': 'Set your school\'s daily rhythm \u2014 when each period starts and ends, break timings, assembly duration, and whether Saturday is a working day. Configure substitution rules for when a teacher is absent, and whether teachers can swap periods among themselves.|Teachers see their daily schedule based on your bell timings. Students see their class timetable. The Vice Principal uses your substitution rules to handle absent teacher periods. If you change a period timing here, the entire school schedule adjusts.',
  'Leave Policy Configuration': 'Define leave rules for your staff \u2014 how many casual leaves, sick leaves, and earned leaves per year. Set special rules like the sandwich rule (do weekends between leave days count?), carry-forward limits, and who approves whose leave (e.g., HOD approves teacher leave, then Principal gives final approval).|Teachers apply for leave and see their balance based on your settings. The HR Manager tracks all leave records. Principals and Vice Principals see approval queues based on the approval chain you define here.',
  'Visitor & Pickup Rules': 'Configure how visitors enter your campus and how students are released at dismissal. Set verification methods \u2014 should parents show OTP, photo ID, or be on an authorized person list? Define different rules for different visitor types (parents, vendors, government officials). Control whether parents can access campus CCTV feeds.|Security guards follow these rules at the gate. Parents get OTP or pre-register visits through their portal. The Receptionist uses these settings when logging visitors. The Principal can review visitor reports.',
  'Certificate Configuration': 'Set up the certificates your school issues \u2014 Transfer Certificate (TC), Bonafide, Character Certificate, Migration Certificate, etc. Configure auto-numbering (so each certificate gets a unique serial number), digital signatures, QR codes for verification, and the approval chain before a certificate is printed.|When a parent or student requests a certificate through the portal, the system follows your approval workflow. The school office generates certificates using your templates. QR codes let anyone verify a certificate is authentic.',
  'Library Configuration': 'Configure your school library \u2014 how many books a student can borrow, loan duration, renewal limits, and overdue fines. Enable digital library access and barcode scanning if your library uses it.|Students search and borrow books based on your rules. Parents get notified about overdue books. The library staff uses your scanning and cataloguing settings daily.',
  'Canteen / Meal Configuration': 'If your school has a canteen, set up pre-ordering, wallet system for cashless payments, and allergy tracking (important for student safety). Configure meal types \u2014 does your canteen serve breakfast, lunch, snacks? If you have a preschool wing, set up special meal plans for young children.|Parents can top up their child\'s meal wallet and track what they eat. Students order meals through the portal. Teachers on canteen duty use these settings for supervision.',
  'Hostel Configuration': 'For boarding schools \u2014 configure room types (single, double, dormitory), mess management, visitor rules for hostel visitors, warden assignments, and curfew timings. Set up emergency contacts and hostel-specific fee components.|The Hostel Warden manages daily operations using these settings. Boarding students see their room and mess details. Parents of hostellers can view hostel fees and communicate with the warden.',
  'Inventory & Asset Configuration': 'Track your school\'s physical assets \u2014 furniture, computers, lab equipment, sports gear, stationery. Set up asset tagging, stock alerts (when items run low), purchase approval chains (small purchases approved by HOD, large ones need Trust approval), and depreciation tracking.|The school admin tracks all assets. Department heads request purchases that flow through your approval chain. The Account Head processes purchase orders and tracks depreciation for accounting.',
  'Compliance & Quality Configuration': 'If your school follows a quality assessment framework like SQAAF, NAAC, or CBSE affiliation norms, configure it here. Set audit schedules, compliance domains (academic quality, infrastructure, safety), and maintain required documents.|The Principal prepares for audits using your compliance checklist. The school admin collects and uploads required documents. Trustees can review compliance scores and audit readiness.',
  'Homework & Assignment Configuration': 'Set rules for homework \u2014 can students submit online, offline, or both? What\'s the file size limit for uploads? Is there a grace period for late submissions? Enable plagiarism checks if needed.|Teachers create and grade assignments using your rules. Students see submission deadlines and upload homework through the portal. Parents track pending homework and get notifications based on your settings.',
  'Enquiry & Admission Configuration': 'Manage the entire journey from enquiry to admission. Configure lead sources (walk-in, website, referral), follow-up reminders, application form fields, required documents, and how seats are allocated per grade.|The Receptionist registers enquiries and tags their source. The School Admin processes applications and manages seat allocation. Parents fill out the online application form you configure here. The Principal monitors conversion rates.',
  'Online Payment Configuration': 'Set up your payment gateway (Razorpay, PayU, CCAvenue) and payment policies \u2014 can parents make partial payments? Is there a convenience fee for online payments? What\'s the refund policy? Configure auto-receipt generation after successful payment.|Parents use your gateway settings when paying fees online. The Account Head reconciles payments and processes refunds. Auto-generated receipts are available to parents instantly after payment.',
  'Parent Portal Configuration': 'Control exactly what parents see when they log in \u2014 fee payment, attendance records, homework tracker, exam results, communication, transport tracking. You can disable any feature to simplify the parent experience. Set when report cards become visible and how parents communicate with staff.|Every toggle here directly shows or hides a feature on the parent\'s login screen. Teachers\' interaction options with parents also depend on your communication mode setting.',
  'Student Portal Configuration': 'Control what students can access in their portal \u2014 attendance history, library, homework submissions, exam results, timetable. Disable modules that aren\'t relevant for your students.|Each toggle directly controls whether a student sees that module when they log in. Keeping it simple helps students focus on what matters.',
  'Alumni Configuration': 'Set up an alumni engagement portal \u2014 networking directory, donation collection, mentorship programs, job board, and event registration. Keep your school connected with former students.|Alumni access the portal features you enable here. The school admin manages alumni records. Trustees can track donations and alumni engagement metrics.',
  'Analytics & BI Configuration': 'Enable advanced analytics \u2014 predictive insights (which students are at risk of dropping out?), trend analysis (how has attendance changed over 3 years?), and custom dashboard widgets. Configure how long historical data is retained for analysis.|The Principal and Trustee see analytics dashboards based on your settings. Data retention affects how far back reports can go. Some features may require a higher subscription tier.',
  'Report Engine Configuration': 'Automate report generation \u2014 schedule daily attendance summaries, weekly fee collection reports, or monthly HR reports to be emailed automatically. Configure export formats (PDF, Excel, CSV) and who receives each report.|Principals receive scheduled reports in their inbox without asking. The Account Head gets financial reports on their schedule. Any admin can download reports in the formats you enable.',
  'API & Integration Configuration': 'Connect your school ERP with third-party tools \u2014 Tally for accounting, SMS providers for notifications, biometric devices for attendance, GPS providers for transport tracking. Set API rate limits to prevent misuse. There is a master switch to disable all integrations in case of emergency.|The Account Head benefits from Tally integration. Communication module uses your SMS/email provider. Attendance and transport modules connect to hardware devices through settings here.',
  'Branding & White-label Configuration': 'Make the ERP look like your school\'s own platform. Set your school logo, brand colors, and custom domain (e.g., portal.yourschool.com instead of a generic URL). Customize email and SMS templates with your school branding.|Parents, students, and staff all see your school branding when they log in. Email notifications carry your school logo and colors. Certificates and reports use your letterhead.',
  'School Identity Configuration': 'Enter your school\'s core details \u2014 official name, board affiliation (CBSE, ICSE, State Board), address, contact information, trust name, and established year. Set up working days, shifts (if you run morning and afternoon shifts), and daycare/extended hours for working parents.|This information appears on every certificate, report card, and official communication. It is the foundation that all other modules reference for your school\'s identity.',
  'Data Privacy & Compliance': 'Configure data protection policies required by DPDP Act 2023 and GDPR. Manage consent collection for student data, photos, and biometric processing. Set data retention periods, breach notification protocols (72-hour mandatory window), and handle right-to-erasure requests from parents and staff.|Every user\u2019s personal data is governed by these settings. Parents see consent forms based on your configuration. The DPO receives automated breach alerts. Erasure requests flow through the Principal for approval.',
  'Demo Data Seeder': 'Seed realistic demo data for trial accounts and sales demonstrations. Populate students, staff, fee transactions, attendance records, and exam results with one click per domain. Includes a danger zone to clear all seeded data.|Sales teams use this to show prospects a fully populated school ERP. Trial accounts get realistic data instantly. Never use on production school accounts \u2014 demo data mixes with real data and cannot be separated.',
  'Mobile App Configuration': 'Configure mobile-specific features \u2014 pull-to-refresh behaviour, offline data caching, push notification frequency, biometric login, geofence-based staff attendance, and data saver mode. Control which features each role (teacher, parent, student, driver, security) sees on mobile. Manage app version control, force-update rules, and maintenance mode.|Every mobile user\u2019s experience is shaped by these settings. Teachers mark attendance via geofence. Parents track buses and pay fees on mobile. Security guards verify visitors. Version control ensures all users run a supported app version.',
  'Onboarding Wizard': 'A guided step-by-step setup for new schools joining the platform. Walk through entering school info, choosing your academic structure, selecting which modules you need, and creating the first admin account. Complete this once \u2014 everything else builds on top of it.|All dashboards and modules depend on the onboarding data. The School Admin you create here is the first user who can access the system and start detailed configuration.',
  'Subscription Management': 'View your current plan, check how much of your quota you are using (active users, storage, SMS), compare available plans, and manage billing. Upgrade or downgrade as your school\'s needs change.|The features available across every module depend on your subscription plan. Usage limits (number of students, SMS count, storage) are enforced based on what is shown here.',
  'Roles & Permissions': 'Define who can do what in the system. For each role (Teacher, Principal, Account Head, etc.), toggle View, Create, Edit, Delete permissions per module. Create custom roles, set up role hierarchy (child roles inherit parent permissions), and control data visibility \u2014 for example, a teacher sees only their class, but a Principal sees all classes.|Every button, page, and data element across all 14 dashboards is controlled by permissions set here. If a teacher cannot see exam results, this is where you check and fix it.',
  'Backup & Export': 'Set up automatic data backups (daily, weekly, or custom schedule) so your school data is always safe. Export data in CSV, Excel, or JSON format for migration or external reporting. Restore from a backup if something goes wrong.|The school admin gets peace of mind with automatic backups. Data export is useful for board submissions, auditor requests, or migrating to a new system.',
};

export const SECTION_INFO: Record<string, string> = {
  // ── Fee Configuration ──
  'Fee Template': 'Choose how your school charges fees. "Simple Annual" means one lump-sum amount per grade per year \u2014 simplest for small schools. "Component-Based" means you break fees into parts (tuition, transport, lab, etc.) with separate amounts \u2014 best for schools that want detailed receipts. "Term-Wise" splits the year into terms with separate billing per term.|Parents see their fee structure differently based on your choice. Simple Annual shows one total. Component-Based shows a detailed breakdown on every receipt. Term-Wise shows payment due per term. The Account Head\'s collection workflow also changes accordingly.',
  'Fee Heads': 'These are the individual fee components you charge \u2014 like Tuition Fee, Transport Fee, Lab Fee, Activity Fee, etc. Toggle each one on or off, and set how often it is billed (monthly, quarterly, yearly, or one-time). Only the fee heads you enable here will appear when setting grade-wise amounts.|When parents view their fee breakdown, they see exactly these heads. The Account Head collects against these heads. If you turn off "Lab Fee" here, it disappears from everywhere \u2014 receipts, reports, and the payment portal.',
  'Grade-wise Fee Amounts': 'This is the actual money table \u2014 how much each grade pays for each fee head. Nursery typically has the lowest fees and Grade 12 the highest, with gradual increases. These values drive every fee receipt, payment request, and financial report in the system.|Parents see these exact amounts on their fee portal. The Account Head uses these for collection targets. Concession calculations are applied on top of these base amounts. If you change an amount here, all pending invoices update.',
  'Payment Configuration': 'Choose which payment methods your school accepts \u2014 UPI, cash, cheque, net banking, credit/debit cards. Set the billing cycle (how often bills are generated) and the due date (day of month by which parents should pay).|Parents see only the payment options you enable here. The Account Head\'s counter shows your accepted modes. The billing cycle determines when the system generates new invoices automatically.',
  'Late Fee Rules': 'If you want to penalize late payments, enable this and set the amount (per day, per week, or flat), grace period (how many days after due date before penalty kicks in), and a maximum cap so penalties don\'t become unreasonable.|Parents see late fee charges added to their pending amount after the grace period. The Account Head\'s collection reports include late fee calculations. The cap ensures penalties stay fair.',
  'Concession & Scholarship Master': 'If your school offers fee discounts \u2014 like sibling discount for parents with multiple children, merit scholarships for toppers, or staff child concessions \u2014 enable them here. Set the discount percentage or fixed amount, and whether principal approval is needed before applying.|When the Account Head or School Admin applies a concession to a student, only the types enabled here will appear as options. Parents will see the concession on their fee receipts.',
  'Concession Approval Workflow': 'Enable this if you want concessions to go through an approval chain before they take effect \u2014 for example, Accounts Officer recommends, Principal approves, and Trust gives final sign-off. Set a threshold below which concessions auto-approve without waiting.|The Principal sees pending concession approvals in their queue. The Account Head can only apply approved concessions. Parents see "Pending Approval" status until the chain completes.',
  'Fee Defaulter Blocking Rules': 'Decide what happens when parents don\'t pay fees on time. You can block report card downloads, prevent Transfer Certificate generation, or hold back exam hall tickets. Enable the auto-reminder option so parents get a warning before any blocking action kicks in.|Students and parents see a message explaining why a service is blocked. Teachers are prevented from releasing report cards for blocked students. The School Admin can see a full defaulter list.',
  'Fee Reminder Schedule': 'Set up automatic reminders that go out before and after the fee due date. For example: 7 days before due date via SMS, 1 day after via SMS + Email, 15 days after via SMS + Phone call. Escalating channels help ensure parents don\'t miss payments.|Parents receive these reminders on their phone and email. The Account Head can track which reminders have been sent. The system handles this automatically \u2014 no manual effort needed.',
  'Payment Modes': 'Detailed settings for each payment method \u2014 processing fees (does UPI have a 0.5% charge?), whether a receipt is generated automatically, and whether reconciliation is automatic or needs manual verification. Set one mode as the default for the school counter.|The Account Head uses these settings for daily reconciliation. Processing fees may be absorbed by the school or shown to parents. Auto-receipt saves time at the fee counter.',

  // ── Academic Configuration ──
  'Academic Year': 'Set the start and end dates of your current academic year (e.g., April 1 to March 31, or June 1 to May 31). Every date-dependent feature in the ERP \u2014 attendance calculations, exam scheduling, fee billing cycles, promotions \u2014 uses these dates as boundaries.|All dashboards show the current academic year context. Exam scheduling is bounded by these dates. Attendance working-day counts are calculated within this range.',
  'Subject Master List': 'Add the subjects taught in each grade. When you add a subject to one grade, it appears as a suggestion for other grades so you can quickly add it. You can rename or remove subjects per grade. This list drives subject dropdowns across the entire ERP.|Teachers see their assigned subjects from this list. The timetable uses these subjects to create period schedules. Exam marks entry shows these subject names. Report cards list these subjects.',
  'Section Configuration': 'Define section names for your school (A, B, C, D...) and assign them to each grade with a student capacity per section. For example, Grade 5 might have sections A, B, C with 40 students each.|Teachers are assigned to class-sections from this list. Attendance is taken section-wise. The timetable creates separate schedules per section. Student allocation during admission uses these capacities.',
  'House System': 'If your school has an inter-house system for sports day, cultural events, or competitions, set up house names, colors, and captains here. Students are assigned to houses for team activities throughout the year.|Students see their house assignment in their profile. Teachers use houses for organizing inter-house events. The Principal can view house-wise participation reports.',
  'Preschool Groups': 'If you have a preschool wing, configure age-based group names and maximum capacity for each level \u2014 Nursery (2-3 years), Jr. KG (3-4 years), Sr. KG (4-5 years). Give them friendly names like "Butterflies" or "Explorers".|Teachers see these group names instead of formal class names for preschool. Parents of preschoolers see the group name on their child\'s profile. Capacity limits help manage admissions.',
  'Holiday Calendar': 'Enter all school holidays and vacations for the academic year \u2014 national holidays, religious observances, Diwali break, summer vacation, etc. You can add single-day holidays or multi-day ranges.|The attendance module automatically skips holidays. Teachers see holidays on their calendar. Parents get holiday notifications. Working day calculations exclude these dates from attendance percentage.',
  'Recurring Holidays': 'Set weekly off-days \u2014 like every Sunday off, or alternate Saturdays off. These combine with the holiday calendar to calculate total working days for the year.|Timetable skips these days when generating weekly schedules. Attendance calculations use this to determine the correct "total working days" denominator.',
  'Terms / Semesters': 'Divide your academic year into terms or semesters with specific start and end dates \u2014 for example, Term 1 (April-July), Term 2 (August-November), Term 3 (December-March). Exams, report cards, and fee billing can all be term-wise.|Term-wise exams are scheduled within these date ranges. Report cards can show term-wise results. Fee billing generates invoices per term if you chose the term-wise fee template.',
  'Academic Year History': 'View past academic years and whether students were promoted/rolled over. This is a reference log \u2014 useful for auditing and understanding historical data when migrating or looking at multi-year trends.|School Admin can reference previous years\' data. Data migration uses this as a reference for importing historical records.',
  'Demographics Configuration': 'Set the dropdown options for religion, caste category (General, OBC, SC, ST), and mother tongue that appear during student admission and profile editing. These should match your local government requirements (e.g., RTE quota categories).|These options appear on the student admission form. The School Admin uses them for RTE compliance reporting. Government reports and demographic analysis use this data.',

  // ── HR & Payroll ──
  'Departments': 'List your school\'s departments \u2014 Teaching, Administration, Accounts, IT, Housekeeping, Sports, etc. Every staff member is assigned to one department, which is used for HR reports, leave policies, and departmental budgeting.|HR Manager filters staff by department. Leave policies can differ by department. The Principal sees department-wise reports. Payroll can be processed department by department.',
  'Designations': 'List staff designations/titles used in your school \u2014 Principal, Vice Principal, Senior Teacher, Teacher, Lab Assistant, Accountant, Peon, etc. These appear on staff profiles, ID cards, and are used for salary structures.|HR Manager assigns designations to staff profiles. Certificates show the signatory\'s designation. The staff directory displays designations. Salary structures can vary by designation.',
  'Salary Structure': 'Define earning components (Basic Pay, HRA, Dearness Allowance, Special Allowance) and deductions (PF, Professional Tax, TDS, ESI) with their percentages of basic pay. This creates the payslip template for all staff.|Teachers and staff see their payslips broken down by these components. The Account Head processes salary using this structure. PF and TDS filings use the deduction percentages you set.',
  'Pay Cycle': 'Set how often salary is paid (monthly or bi-weekly) and on which date of the month it is processed. For example, "Monthly, processed on 28th" means salary is calculated and disbursed on the 28th of every month.|The HR Manager follows this schedule for payroll processing. Teachers know when to expect their salary. The Account Head schedules disbursement on this date.',
  'Staff Attendance Methods': 'Choose how staff check-in and check-out is recorded \u2014 biometric fingerprint, RFID card, manual register, mobile app GPS, or a combination. You can enable multiple methods simultaneously.|Teachers and staff use the method(s) you enable here. The HR Manager reconciles attendance from these devices. The Principal sees staff attendance overview. Security guards manage biometric/RFID devices at entry.',
  'Staff Onboarding Checklist': 'Create a checklist of steps every new hire must complete \u2014 submit documents (ID proof, qualification certificates), attend orientation training, receive laptop/ID card, complete background verification, sign appointment letter.|The HR Manager tracks each new hire\'s checklist progress. New staff see their pending tasks. The Principal can see onboarding status for recent hires.',
  'HR Letter Templates': 'Define the types of HR letters your school issues \u2014 offer letter, appointment letter, relieving letter, experience certificate, increment letter, warning letter. Templates are used when generating these letters for staff.|The HR Manager generates letters from these templates. Staff can access their letters (offer, appointment) through their dashboard. The Principal approves certain letter types.',
  'Performance Appraisal Stages': 'Set up the multi-stage appraisal process \u2014 for example: (1) Teacher fills self-assessment, (2) HOD reviews and scores, (3) Principal gives final rating, (4) Management review. Each stage has a time limit for completion.|Teachers fill in their self-appraisal during review season. HODs and Principals see their review queues. The HR Manager tracks completion across all staff.',

  // ── Transport ──
  'Transport Policy': 'Set your school\'s transport ground rules \u2014 do you operate your own fleet or use contracted vehicles? Is a lady attendant required on every bus? Is GPS tracking mandatory? Can transport fees be collected at the counter or only online?|The Transport Head follows these policies for daily operations. Parents see whether live GPS tracking is available. Security guards check vehicles against your fleet policy.',
  'Routes': 'Add bus routes with stop names, pickup/drop timings, assigned vehicle, and driver. Each route serves a geographic area. Students are mapped to routes based on their home address.|The Transport Head manages daily route operations. Parents see their child\'s route, stop, and timing. Students know their bus number and pickup time. Security guards verify vehicles by route.',
  'Vehicle Fleet': 'Register all school vehicles \u2014 bus number, type (bus/van/tempo), seating capacity, GPS device status, insurance expiry, and PUC validity. Keep this updated for compliance.|The Transport Head schedules maintenance based on vehicle data. Security guards verify vehicle registration at the gate. Compliance tracking alerts you before insurance or PUC expires.',
  'Driver Details': 'Enter driver information \u2014 name, phone number, license number, assigned route, and badge status. Parents need to know who is driving their child.|The Transport Head assigns drivers to routes. Parents can see the driver\'s name and contact for their child\'s bus. Security guards verify driver identity. License expiry is tracked for compliance.',
  'Tracking & Safety': 'Enable safety features \u2014 speed alerts (notify if bus exceeds speed limit), SOS panic button, real-time GPS tracking, geo-fencing (alert if bus deviates from route), girl child safety protocols, and first aid kit tracking on every vehicle.|Parents can track the bus live on a map. The Transport Head gets speed and route deviation alerts. The Principal sees a safety compliance dashboard.',
  'Transport Fee Model': 'Choose how transport fees are calculated \u2014 flat rate (same for everyone), distance-based (farther stops pay more), or stop-based (fixed price per stop). This determines each student\'s transport fee amount.|The Account Head collects transport fees based on this model. Parents see their transport fee calculated according to their child\'s stop distance. Fee reports separate transport revenue.',
  'Pickup Policies': 'Set rules for releasing students at dismissal \u2014 should parents verify via OTP sent to their phone? Must they be on a pre-authorized person list? Is photo ID matching required? These rules protect student safety at pickup time.|Security guards follow these steps before releasing any student. Parents receive OTPs or pre-register authorized persons through their portal. The Transport Head oversees the dismissal process.',
  'Student Commute Tagging': 'Tag how each student gets to and from school \u2014 school bus, walk-in, private vehicle, or auto-rickshaw. This helps with transport planning and managing the dismissal process.|The school admin uses this for transport planning and bus allocation. Security guards know which students are bus riders vs. walkers at dismissal. Transport fee applies only to bus-tagged students.',
  'Transport Manager Permissions': 'Control what the Transport Manager role can do \u2014 edit routes, manage drivers, schedule maintenance, view transport fees, assign students to routes, and run reports. Toggle each permission on or off.|The Transport Head sees only the features you enable here. The school admin can adjust these permissions if the transport manager\'s responsibilities change.',

  // ── Attendance ──
  'Marking Methods': 'Select which attendance marking methods your school uses \u2014 biometric scanner, RFID card tap, manual register entry, mobile app (teacher marks from phone), or QR code scan. You can enable more than one method.|Teachers see the marking interface matching your selected method. If you enable biometric, students scan their finger. If you enable mobile app, teachers mark attendance from their phone.',
  'Frequency & Timing': 'Choose how often attendance is taken \u2014 once a day (morning roll call), twice a day (morning + afternoon), or every period (period-wise tracking). Set the grace period for late arrivals and the half-day cutoff time.|Teachers follow this marking frequency. Period-wise tracking means every teacher marks attendance at the start of their class. Parents get notifications based on the timing you set.',
  'Auto-Notification Rules': 'Set up automatic alerts that fire when attendance events happen \u2014 instant SMS when a child is absent, email after 3 continuous absences, alert to Principal after 7 continuous absences. Each rule can be toggled independently.|Parents get real-time absence alerts on their phone. Teachers trigger these notifications just by marking attendance. The Principal gets escalation alerts for chronic absentees.',
  'Attendance Types': 'Define the statuses teachers can choose when marking attendance \u2014 Present, Absent, Late, Half-day, Excused Absence, Medical Leave, On Duty, etc. You can add custom types specific to your school.|Teachers see these status options in their marking dropdown. Parent notifications mention the specific status. Reports show breakdowns by attendance type.',

  // ── Exams & Grading ──
  'Grading System': 'Choose your fundamental grading method \u2014 Percentage (marks out of 100), Grade-Based (A, B, C letter grades), CGPA (cumulative grade point average), or Competency-Based (skill levels). This affects how all results are displayed school-wide.|Teachers enter marks/grades matching your chosen system. Students and parents see results in this format. Report cards display the grading method you select here.',
  'Grade Boundaries': 'Define what each grade means in terms of marks and grade points \u2014 for example, A1 = 91-100 marks = 10.0 grade points, A2 = 81-90 = 9.0, B1 = 71-80 = 8.0, and so on. The system automatically assigns grades based on marks entered by teachers.|Teachers just enter raw marks \u2014 grades are calculated automatically using your boundaries. Students see both marks and grades. Report cards show the complete grade table.',
  'Report Card Template': 'Choose the visual layout of your printed report card \u2014 where the school logo goes, how subjects are listed, whether to include co-curricular grades, attendance summary, teacher remarks, and principal signature. Preview before finalizing.|Students and parents see report cards in this exact format. Teachers know which fields they need to fill (remarks, co-curricular grades). The Principal approves the final template.',
  'Rank Display Options': 'Decide whether to show student rankings on report cards \u2014 class rank, section rank, and overall percentile. Some education boards discourage ranking. You can toggle each ranking type independently.|If enabled, students and parents see rank on report cards. If disabled, no ranking appears. Teachers may still see internal rankings for their reference even if hidden from report cards.',
  'Exam Schedule': 'Enter specific exam dates, times, and subjects \u2014 for example, "Unit Test 1: English on March 15, 9:00-10:30 AM." This drives the exam timetable for students and invigilation duties for teachers.|Students and parents see the exam timetable. Teachers get invigilation duty assignments based on this schedule. The Principal coordinates exam logistics using these dates.',
  'Exam Types': 'Define your exam categories and their weightage toward the final result \u2014 for example, Unit Test (20%), Mid-Term (30%), Final (50%). The total should add up to 100%. This determines how term-wise marks combine into cumulative results.|Teachers create exams under these categories. Students see results broken down by exam type. Report cards calculate cumulative scores using your weightages.',
  'Report Card Template Fields': 'Toggle which information appears on the printed report card \u2014 school logo, principal\'s signature, attendance summary, co-curricular grades, teacher remarks, health record, parent signature field. Turn off anything you don\'t need.|The printed report card includes only the fields you enable here. Teachers are asked to fill only the enabled fields (like remarks). Parents see exactly what you choose to show.',

  // ── Communication ──
  'DM Permission Matrix': 'Control who can send direct messages to whom. For example: parents can message their child\'s class teacher but not the Principal directly. Teachers can message parents but students cannot initiate DMs to teachers. Set these rules to maintain appropriate communication boundaries.|Every user\'s "New Message" button shows only the people they\'re allowed to contact based on this matrix. If you block Student\u2192Principal, students won\'t even see the Principal in their contact list.',
  'Parent Communication Mode': 'Set the level of communication access for parents \u2014 Full Chat (parents can message freely), Announcement-Only (parents can only view school announcements, no two-way messaging), or Emergency-Only (parents can only send urgent messages).|Parents see messaging capabilities matching your setting. Full Chat gives parents a complete chat experience. Announcement-Only makes the parent portal read-only for communications.',
  'Group Creation Permissions': 'Decide who can create group chats \u2014 Admin Only (tightest control), Admin + Teachers (teachers can create class groups), or All Roles (everyone can create groups). Prevents unnecessary group proliferation.|Teachers see the "Create Group" button only if you allow it. Admin-only means the school admin manually creates all groups. This controls group chat creation across all dashboards.',
  'Default Auto-created Groups': 'The system can automatically create groups when classes and staff are set up \u2014 one parent group per class (e.g., "Grade 5-A Parents"), a staff room group, and department groups. These save time and ensure standard groups exist.|Teachers find their class parent groups ready-made. Parents are automatically added to their child\'s class group. Staff see a common staff room group for school-wide communication.',
  'Chat Storage & Retention': 'Set how long chat messages and shared files are stored before the system archives or deletes them \u2014 for example, 1 year, 2 years, or unlimited. Longer retention means more storage usage but better history.|Users can scroll back through messages within your retention period. Old messages beyond the retention period are archived. This affects storage costs on your subscription plan.',
  'File Sharing': 'Control what file types users can share in chat \u2014 images, PDFs, Word documents, videos, audio files, spreadsheets. Block file types you don\'t want shared to prevent misuse and manage storage.|Users see upload restrictions matching your settings. Teachers can share worksheets and PDFs if enabled. Blocking videos saves storage. This applies to all chat conversations.',
  'Message Templates': 'Create pre-built message templates with variable placeholders like {student_name}, {class}, {due_date}, {amount}. Use them for fee reminders, absence notifications, event invitations, and more. Templates work across SMS, email, WhatsApp, and push notifications.|The system uses these templates for automated messages. Teachers can pick templates for quick communication. The school admin manages and updates template content.',

  // ── Timetable & Bell ──
  'Bell Schedule': 'Set the start and end time for every period in the school day \u2014 Period 1 (8:00-8:40), Period 2 (8:40-9:20), Recess (10:00-10:30), etc. This is the heartbeat of your school\'s daily schedule.|Teachers see their period timings based on this schedule. Students see when each class starts. The school bell system (if automated) follows these timings exactly.',
  'Saturday Schedule': 'Choose whether Saturday is a full working day, an off day, or an alternate Saturday (working on 1st and 3rd Saturdays, off on 2nd and 4th). This affects the weekly timetable pattern.|Teachers\' weekly schedule includes or excludes Saturday based on this. Attendance calculations factor in Saturday status. Parents see the correct school calendar.',
  'Zero Period': 'Enable an optional early-morning period before regular school hours \u2014 useful for remedial classes, special coaching for board exam students, or extra subjects like music/art. Not all students need to attend.|Teachers assigned to zero period see it on their schedule. Students in remedial or coaching programs have an earlier start time. Parents are informed of the adjusted timing.',
  'Assembly': 'Set the duration of morning assembly (e.g., 15 minutes or 20 minutes). The first academic period starts after assembly ends. This time is deducted from the available teaching time.|Teachers on assembly duty see this in their schedule. Students\' first period adjusts based on assembly duration. The timetable automatically accounts for assembly time.',
  'Teacher Substitution': 'When a teacher is absent, how should their periods be covered? Choose manual assignment (Vice Principal picks a substitute), auto-suggest (system recommends teachers with free periods who teach the same subject), or both.|The Vice Principal uses this to fill absent teacher slots every morning. Substitute teachers see the duty on their dashboard. Students see the updated schedule for the day.',
  'Period Swaps': 'Allow teachers to exchange periods with each other \u2014 for example, the English teacher and Math teacher swap their 2nd period with 5th period. Both teachers must agree. This provides flexibility without needing admin intervention.|Teachers see a "Request Swap" option on their timetable. The other teacher gets a notification to accept or decline. The Vice Principal can see all swaps for oversight.',
  'Rooms & Infrastructure': 'List all rooms, labs, and facilities in your school with their capacity and equipment (projector, smart board, etc.). The timetable uses this for room allocation \u2014 ensuring a physics lab period is scheduled in the actual physics lab.|Teachers see their assigned room for each period. The timetable generator ensures no two classes are assigned the same room at the same time. The school admin tracks facility usage.',

  // ── Leave Policy ──
  'Leave Types & Annual Allocation': 'Define leave categories and how many days each staff member gets per year \u2014 for example, 12 Casual Leaves, 10 Sick Leaves, 15 Earned Leaves. Set whether unused leaves carry forward to next year or can be encashed.|Teachers and staff see their leave balance per type. The HR Manager tracks consumption. At year-end, carry-forward rules determine what rolls over. Encashment affects payroll calculations.',
  'Leave Rules': 'Set special rules for leave calculation \u2014 does half-day count as 0.5 or 1 day? If someone takes Friday and Monday off, do Saturday-Sunday count as leave days (sandwich rule)? Is a medical certificate required after 3 consecutive sick days? Are leave rules different during the probation period?|The HR Manager applies these rules when processing leave. Teachers see their effective leave balance reflecting these rules. Payroll deductions follow the rules you set.',
  'Teaching Staff Approval Chain': 'Set the approval hierarchy for teacher leave requests \u2014 for example: HOD approves first, then Vice Principal, then Principal. Each level has a time limit (e.g., 2 days) before the request auto-escalates to the next level.|Teachers submit leave and see it move through this chain. Each approver sees requests in their queue. If an approver doesn\'t act in time, the request escalates automatically.',
  'Non-Teaching Staff Approval Chain': 'Set a separate approval hierarchy for non-teaching staff (admin, peon, security, etc.) \u2014 for example: Department Head approves, then HR Manager gives final approval. This is separate from the teaching staff chain.|Non-teaching staff submit leave through this chain. The admin supervisor and HR Manager see their approval queues. Different rules may apply for different staff categories.',

  // ── Visitor & Pickup ──
  'Pickup Verification Method': 'Choose how the school verifies identity during student pickup \u2014 OTP sent to parent\'s phone, photo matching from pre-uploaded photos, pre-authorized person list, or RFID card tap. Multiple methods can be combined for extra safety.|Security guards follow this verification process at the gate. Parents receive OTPs or pre-register authorized persons through the parent portal. This is a critical child safety feature.',
  'Visitor Type Rules': 'Set different rules for different types of visitors \u2014 parents may enter freely with phone OTP, vendors need prior appointment, government officials get immediate access, alumni can visit during designated hours. Each type can have different ID requirements and time limits.|Security guards see type-specific instructions when registering a visitor. The Receptionist follows different protocols per visitor type. The Principal can review visitor logs by type.',
  'Campus CCTV': 'Control whether parents can access live CCTV feeds of common areas (NOT classrooms \u2014 only playground, corridors, cafeteria). Set whether recording access is available and how long recordings are retained.|Parents see a "Live Campus View" option in their portal if enabled. This builds trust with parents while maintaining privacy. The school admin manages camera configurations.',

  // ── Certificates ──
  'Certificate Templates': 'Configure the certificate types your school issues \u2014 Transfer Certificate (TC), Bonafide Certificate, Character Certificate, Conduct Certificate, Migration Certificate. Each type has its own template layout, auto-numbering format, and issuing authority (who signs it).|The school office generates certificates from these templates. Students and parents request certificates through the portal. Auto-numbering ensures every certificate has a unique serial.',
  'Certificate Features': 'Enable security features on your certificates \u2014 digital signature (valid without physical signature), QR code (anyone can scan to verify authenticity), watermark, and anti-tampering measures. These make your certificates trustworthy and verifiable.|Parents and students receive certificates with these security features. External institutions can scan the QR code to verify a certificate is genuine. Digital signatures speed up the issuance process.',
  'Approval Workflow': 'Set the approval chain before a certificate is printed and issued \u2014 for example: Class Teacher verifies student details, Principal approves, Admin prints and dispatches. This ensures accuracy and proper authorization.|Class Teachers see certificate requests for their students. The Principal sees an approval queue. Office staff print only approved certificates. Parents see status updates at each stage.',

  // ── Library ──
  'Loan Rules': 'Set borrowing limits \u2014 how many books can a student borrow at once (e.g., 3), for how many days (e.g., 14 days), how many renewals are allowed, and what is the overdue fine per day.|Students see their borrowing limit when they search for books. Parents get overdue notifications. The library staff enforces these rules at the counter. Fines appear on the student\'s account.',
  'Library Features': 'Enable advanced library features \u2014 digital library (e-books and online resources), barcode scanning (quick check-in/check-out), and reading analytics (track how much each student reads).|Students access the digital library through the student portal if enabled. Library staff scan barcodes for faster processing. The Principal can see reading habit reports.',
  'Book Categories': 'Define how your library catalogue is organized \u2014 Fiction, Non-fiction, Reference, Textbook, Magazine, Science, History, etc. Books are tagged with these categories for easy search and browsing.|Students search and filter books by these categories. Library staff catalogue new books using this list. The school admin sees category-wise collection reports.',

  // ── Canteen ──
  'Canteen Features': 'Enable canteen capabilities \u2014 pre-ordering (students order before break time), digital wallet (cashless payments from a prepaid balance), allergy tracking (flag allergens in each menu item), and dietary safety alerts.|Students use pre-ordering to skip the queue. Parents top up their child\'s wallet and set allergy restrictions. Canteen staff see orders with allergy warnings highlighted.',
  'Meal Types': 'Select which meals your canteen serves \u2014 Breakfast, Morning Snacks, Lunch, Evening Snacks. This determines your menu structure and ordering windows.|Students see ordering options for each enabled meal type. Canteen staff prepare meals based on this schedule. The menu changes per meal type.',
  'Preschool Meal Plan': 'Special meal configuration for nursery and KG children \u2014 smaller portions, allergen-free options by default, and meal tracking so parents know what their toddler ate. This is separate from the main canteen menu.|Parents of preschoolers see daily meal reports. Teachers on preschool duty supervise meals using these settings. The nutritionist plans age-appropriate menus.',

  // ── Hostel ──
  'Hostel Features': 'Configure boarding facilities \u2014 room allocation system, mess management (meal schedules), hostel visitor log, warden assignment per floor/wing, curfew timings, and emergency contact list.|The Hostel Warden uses these settings to manage daily operations. Boarding students see their room, mess schedule, and curfew times. Parents can view hostel details through the parent portal.',
  'Room Types': 'Define accommodation categories \u2014 single room, double sharing, triple sharing, dormitory. Set capacity and monthly charges for each type. This determines room allocation and hostel fee calculation.|The Warden allocates rooms based on available types. Hostel fee is calculated from the room type charge. Students see their room type and roommate details.',

  // ── Inventory ──
  'Inventory Features': 'Enable asset tracking capabilities \u2014 asset tagging (label every item with a unique code), stock alerts (get notified when supplies run low), depreciation tracking (calculate asset value over time), and barcode scanning for quick inventory audits.|The school admin tracks all physical assets. Department heads see their allocated assets. The Account Head tracks depreciation for financial records.',
  'Asset Categories': 'Organize your inventory by categories \u2014 Furniture, IT Equipment (computers, projectors), Lab Apparatus, Sports Equipment, Stationery, Vehicles. Each category can have different depreciation rates and maintenance schedules.|The school admin runs category-wise reports. Purchase requests are categorized for easier approval. Budget allocation can be tracked per category.',
  'Purchase Approval Tiers': 'Set who approves purchases based on amount \u2014 for example, items under \u20B95,000 approved by HOD, \u20B95,000-50,000 by Principal, above \u20B950,000 by Trust. This controls procurement workflow and prevents unauthorized spending.|Purchase requests route through the correct approver based on amount. The Account Head processes only approved purchases. The Principal and Trust see their approval queues.',

  // ── Compliance ──
  'Framework & Schedule': 'Select your school\'s assessment framework \u2014 SQAAF (School Quality Assessment and Accreditation Framework), NAAC, or CBSE affiliation norms. Set how often audits happen (annually, bi-annually). The system prepares compliance checklists based on your framework.|The Principal uses this to prepare for upcoming audits. The school admin tracks which compliance items are complete. Trustees see audit readiness scores.',
  'Compliance Domains': 'These are the specific areas assessed during audits \u2014 Academic Quality, Infrastructure, Safety & Security, Governance, Teacher Quality, Student Outcomes, etc. Each domain gets a score during assessment.|The Principal prepares evidence for each domain before an audit. The school admin uploads supporting documents per domain. Inspectors evaluate domain-by-domain during visits.',
  'Required Documents': 'List documents required for student admission (birth certificate, Aadhar card, previous school TC, photos) and staff joining (qualification certificates, ID proof, experience letters). The system creates upload checklists from this list.|Parents see this checklist during admission and upload documents accordingly. HR uses the staff checklist during onboarding. The school admin verifies document completeness.',

  // ── Homework ──
  'Submission Settings': 'Set homework submission rules \u2014 can students submit online (upload files), offline (submit in class), or both? What is the maximum file size for uploads? Is there a grace period after the deadline? What penalty applies for late submissions?|Teachers create assignments following these rules. Students see submission options and deadlines. Parents get notifications about pending and overdue homework.',
  'Assignment Features': 'Enable advanced homework features \u2014 plagiarism detection (check if students copied), auto-grading for multiple-choice assignments, peer review (students evaluate each other), and parent notifications for every assignment.|Teachers get plagiarism reports alongside submissions. Students receive auto-graded results instantly for MCQ assignments. Parents are notified when homework is assigned and when results are shared.',

  // ── Enquiry & Admission ──
  'Admission Settings': 'Configure the admission process \u2014 what fields appear on the application form, which documents are required, whether fees are collected at admission, and how seats are managed per grade.|The Receptionist and School Admin follow this workflow. Parents fill out the application form you design here. Seat availability is tracked automatically based on your grade-wise capacity.',
  'Lead Sources': 'Define where enquiries come from \u2014 Walk-in, School Website, Parent Referral, Newspaper Advertisement, Social Media, Education Fair, etc. Tagging sources helps you understand which marketing channels bring the most admissions.|The Receptionist tags every enquiry with its source. The School Admin runs source-wise conversion reports. The Principal sees which channels are most effective.',
  'Enquiry Sources': 'Detailed tracking of how enquiries are categorized and prioritized for follow-up. Higher-priority sources (like personal referrals) can be set to trigger faster follow-ups than lower-priority ones (like walk-ins).|The Receptionist categorizes enquiries by source. Follow-up reminders fire based on the priority you assign to each source. The school admin reviews source performance regularly.',

  // ── Online Payment ──
  'Gateway & Policy': 'Select your payment gateway provider \u2014 Razorpay, PayU, or CCAvenue \u2014 and set your refund policy (how many days for refund processing, auto-refund for duplicate payments). This is the infrastructure parents use to pay online.|Parents use this gateway when they click "Pay Now" in the fee portal. The Account Head reconciles gateway transactions. Refund requests follow your policy settings.',
  'Payment Features': 'Configure payment behavior \u2014 should receipts be generated automatically after payment? Can parents make partial payments (pay some now, rest later)? Is there a convenience fee for online payments? How is reconciliation handled?|Parents see partial payment options if enabled. Auto-receipts mean instant proof of payment. The Account Head\'s reconciliation process depends on these settings.',

  // ── Critical Locks ──
  'Lockable Fields': 'These are high-impact fields that require OTP verification before changes can be made \u2014 fee structure (prevents accidental fee changes), salary components (prevents payroll errors), and bank details (prevents fraud). Only the registered Trustee\'s phone receives the OTP.|The SSA must request an OTP from the Trustee before editing these fields. This prevents unauthorized changes. The audit log records every locked-field change with before/after values.',
  'Recent Lock Events': 'A tamper-proof history of every OTP-verified change \u2014 who requested the change, what field was changed, when, and the before/after values. Use this to audit sensitive changes.|The SSA can review past changes. Trustees can monitor what has been modified. External auditors can verify the integrity of sensitive data changes.',
  'Authentication Contact': 'The phone number or email that receives OTP codes when someone tries to change a locked field. This should be the Trustee or a senior management representative \u2014 not the SSA themselves.|The Trustee receives OTP requests on this contact. If this number changes, it requires a separate verification process to prevent unauthorized reassignment.',

  // ── Parent Portal ──
  'Portal Features': 'Toggle which features parents can access \u2014 fee payment, attendance tracking, homework viewer, exam results, communication, transport tracking, canteen ordering, certificate requests. Turning off a feature completely hides it from the parent\'s screen.|Parents see only the modules you enable. If you disable "Transport Tracking," parents won\'t see any bus-related features. Teachers\' interaction scope with parents also depends on what is enabled.',
  'Report Card Access': 'Control when parents can see report cards \u2014 immediately after the teacher publishes results, after a set delay (e.g., 3 days for review), or only after the Principal manually approves release. This prevents premature result leaks.|Parents see "Results Available" based on your timing. Teachers have a deadline to enter results before publish. The Principal has control over the release if approval mode is enabled.',
  'Communication Mode': 'Set the messaging level for parents \u2014 Full Chat (parents can message teachers and staff freely), Announcement-Only (parents can only read school announcements, no two-way messaging), or Emergency-Only (parents can only send urgent messages).|Parents\' messaging capabilities match this setting exactly. Full Chat gives a WhatsApp-like experience. Announcement-Only makes the communication tab read-only for parents.',

  // ── Student Portal ──
  'Module-Level Feature Toggles': 'Enable or disable entire modules for the student portal \u2014 attendance history, library catalogue, homework submissions, exam results, timetable view, and more. Keep the student experience focused by disabling modules they don\'t need.|Students see only the modules you turn on. Disabling "Library" hides the entire library section. This helps keep the student portal clean and focused.',

  // ── Alumni ──
  'Alumni Portal Features': 'Configure alumni engagement tools \u2014 networking directory (alumni can find and connect with each other), donation portal (accept contributions for school development), mentorship program (alumni mentor current students), job board (alumni post job opportunities), event registration (reunions, annual days).|Alumni access these features when they log in. The school admin manages alumni records and events. Trustees can track donation amounts and alumni engagement levels.',

  // ── Analytics ──
  'Core Analytics': 'Enable analytics capabilities \u2014 predictive analytics (identify students at risk of dropout or failure), trend analysis (multi-year comparison), benchmarking (compare with other schools on the platform), and custom dashboards. Some features may require a higher subscription tier.|The Principal and Trustee see these analytics on their dashboards. Data-driven insights help with decision-making. The school admin configures which widgets appear.',
  'Dashboard Widgets': 'Choose which analytics widgets show on admin dashboards \u2014 enrollment trends (are admissions going up or down?), fee collection rate, attendance patterns, exam performance distribution, staff attendance, and more.|Principals see their customized dashboard with selected widgets. Trustees see high-level KPI widgets. The school admin can configure different widget sets for different roles.',
  'Data Retention': 'Set how many years of historical data is kept for analytics \u2014 1 year, 3 years, 5 years, or unlimited. Longer retention enables deeper trend analysis but uses more storage (which may affect your subscription tier).|Longer retention means you can compare this year\'s performance with 5 years ago. Compliance requirements may dictate minimum retention periods. Storage usage is tracked in your subscription.',
  'Force-Push Mandatory Dashlet': 'Push a required widget/dashlet to all users of a target role. The dashlet appears on their dashboard and cannot be dismissed until the associated task is completed or the expiry date passes. Use this for urgent school-wide actions like fee payment reminders or form submissions.|All targeted users see the dashlet prominently on their dashboard. The SSA controls the content, target role, and expiry. Non-removable until the configured condition is met.',
  'KPI Threshold Alerts': 'Set red/amber/green thresholds for key performance indicators like attendance rate, fee collection percentage, and exam pass rate. When a KPI falls below the configured threshold, the dashboard indicator changes color and an automatic alert is sent to the Principal and School Admin.|Principals see color-coded KPI cards on their dashboard. School Admins receive threshold breach alerts. Trustees see summary KPI health on their dashboard.',
  'Announcement Lifecycle': 'Control how announcements expire and get archived. Enable auto-archival after a configurable number of days past the expiry date. Optionally notify the sender before archival so they can extend or update the announcement.|Announcements auto-disappear from all dashboards after the configured period. Senders get a heads-up notification before archival. Archived announcements are still searchable but hidden from active feeds.',
  'Locale & Format Settings': 'Set the default currency symbol, date format, timezone, and number formatting for the entire school. These settings affect how dates, amounts, and numbers are displayed across all modules, reports, and portals.|Every user sees dates and currency in the format you set here. Fee receipts show the configured currency symbol. Reports use your date format. Timezone affects scheduled report delivery times.',

  // ── Data Privacy ──
  'Consent Management': 'Define which types of data collection require explicit consent from parents or staff \u2014 personal data, photos/videos, biometric processing, third-party sharing, and marketing communications. Each consent type can be independently toggled.|Parents see consent forms during admission based on these settings. Staff consent is collected during onboarding. The school maintains a consent audit trail for compliance.',
  'Compliance Framework': 'Enable the applicable data protection regulations for your school \u2014 DPDP Act 2023 (mandatory for Indian schools) and GDPR (for schools with EU connections). Set the frequency of privacy audits.|The system enforces data handling rules based on enabled frameworks. Audit schedules are tracked and reminders sent to the DPO. Compliance reports are generated per framework.',
  'Data Retention Policy': 'Set how long personal data is stored before the system auto-purges or anonymizes it. Different data types may have different statutory retention requirements.|Student data is anonymized after the retention period. Financial records follow separate statutory rules. The DPO can override retention for specific cases with documented reasons.',
  'Breach Notification': 'Configure automated data breach notification \u2014 who gets notified (DPO, affected parties), through which channel (email), and within what time window (72 hours per DPDP Act). This is a legal requirement.|The DPO receives immediate alerts when a breach is detected. Affected users are notified within the configured window. The system logs all breach notifications for compliance records.',
  'Right to Erasure': 'Enable parents and staff to request complete deletion of their personal data. Academic and financial records are exempt per statutory requirements. Erasure requests require Principal approval before execution.|Parents see a "Request Data Deletion" option in their profile. The Principal reviews and approves erasure requests. The system maintains a log of all erasure actions for compliance.',

  // ── Demo Data Seeder ──
  'Seed Data by Domain': 'Populate specific data domains with realistic demo records \u2014 500 students, 80 staff, 3 years of fee transactions, 6 months of attendance, and 2 exam cycles. Each domain can be seeded independently.|Demo accounts get a fully populated experience for evaluation. Sales teams can showcase all ERP features with realistic data. Each domain takes a few seconds to seed.',
  'Danger Zone': 'Irreversibly clear all seeded demo data from the system. This removes all fictional records created by the seeder. Use with caution \u2014 this action cannot be undone.|The SSA triggers this when a demo account converts to production. All seeded records are permanently deleted. Real data (if any was entered after seeding) remains unaffected.',

  // ── Mobile App ──
  'Dashboard Behaviour': 'Configure how the mobile dashboard behaves \u2014 pull-to-refresh for manual data updates, offline snapshot caching so users can view last-loaded data without internet, and widget display mode (card layout vs. compact list).|Mobile users experience the dashboard according to these settings. Offline mode is critical for areas with poor connectivity. Widget mode affects screen real estate on small phones vs. tablets.',
  'Mobile-Specific Settings': 'Configure mobile-only features \u2014 push notification frequency (instant vs. batched), biometric login (fingerprint/face), data saver mode for low-bandwidth networks, and geofence-based staff attendance (auto-mark when within school premises).|Teachers use biometric login for quick access. Staff attendance is auto-marked via GPS geofence. Parents on limited data plans benefit from data saver mode.',
  'Role-Specific Mobile Views': 'Control exactly which features each role sees on the mobile app. Security guards see only visitor management and pickup verification. Drivers see routes and boarding lists. Teachers see attendance, timetable, and homework. Parents see fees, communication, and transport tracking.|Each role gets a focused, clutter-free mobile experience. Unnecessary features are hidden to reduce confusion. The SSA can adjust views per role as needs evolve.',
  'Version Control & Updates': 'Manage mobile app deployment \u2014 set the current version, minimum supported version, force-update rules, and maintenance mode. Configure store URLs for Google Play and Apple App Store.|Users on outdated app versions are prompted or forced to update. Maintenance mode displays a full-screen notice on all mobile devices. Store URLs enable one-tap update from within the app.',

  // ── Report Engine ──
  'Email Reports': 'Schedule automatic email delivery of reports \u2014 for example, send the daily attendance summary to the Principal at 10 AM, weekly fee collection report to the Account Head every Monday, monthly staff report to HR on the 1st.|Recipients get reports in their inbox automatically without requesting them. The school admin manages schedules and recipient lists.',
  'Export Formats': 'Choose which file formats are available for report downloads \u2014 PDF (best for printing and sharing), Excel (best for further analysis and accounting), CSV (best for data import/export), Word (best for editing and customizing).|All admin users see download buttons for your enabled formats. The Account Head typically needs Excel for accounting software. The Principal prefers PDF for sharing.',
  'Report Recipients': 'Configure who receives each scheduled report \u2014 select from your staff directory. Different reports go to different people. For example, fee reports go to Account Head and Principal, while HR reports go to HR Manager only.|Selected recipients get reports automatically. The school admin manages these lists. New staff can be added to relevant report distributions.',
  'Auto-Generate Reports': 'Enable automatic report creation on a schedule \u2014 the system generates reports without anyone clicking a button. Set which reports are generated (attendance, fees, HR, compliance) and how often (daily, weekly, monthly).|Reports appear in each recipient\'s dashboard automatically. No manual effort required. The school admin sets the schedule and the system handles the rest.',

  // ── API & Integrations ──
  'Integration Master Switch': 'A global on/off switch for all external integrations. When turned off, no third-party service can connect to your school ERP. Use this as an emergency kill-switch if you suspect a security issue with any integration.|Turning this off immediately disconnects all integrations \u2014 Tally sync stops, SMS delivery pauses, biometric devices disconnect. Only use this in emergencies.',
  'Available Integrations': 'See and manage all third-party services you can connect \u2014 Tally (accounting software sync), Razorpay/PayU (payment gateway), SMS providers (Twilio, MSG91), CCTV systems, biometric devices, and GPS tracking hardware.|The Account Head benefits from Tally integration for automatic accounting entries. The communication module sends SMS through your connected provider. Attendance syncs from biometric devices.',
  'API Rate Limit': 'Set the maximum number of API requests per minute \u2014 prevents any single integration from overloading your system. Higher limits are available on premium plans. Default of 60 requests/minute is sufficient for most schools.|This protects your system from being overwhelmed. If you have many integrations running simultaneously, you may need a higher limit. This is a technical safety setting.',

  // ── Branding ──
  'Custom Domain': 'Use your own web address (e.g., portal.delhipublicschool.edu.in) instead of the default Saaras URL. Parents and staff access the ERP through your school\'s branded URL. Requires DNS configuration (your IT team or Saaras support can help).|Parents type your school\'s URL to access the portal. It looks professional and builds trust. All email links also use your custom domain.',
  'White-label & Templates': 'Remove Saaras branding and use your school\'s identity throughout \u2014 custom email templates (with your logo in the header), SMS templates (school name as sender), and interface branding (your colors on the login page and dashboards).|Every notification email and SMS carries your school\'s branding. The login page shows your school\'s visual identity. Users don\'t see Saaras branding at all.',
  'Visual Identity': 'Upload your school logo and set your primary brand color (e.g., navy blue for Delhi Public School, maroon for Ryan International). These appear on login pages, dashboards, certificates, reports, and all portals.|Every user sees your logo in the header when they log in. Certificates carry your logo. Reports use your brand color for headings and accents.',

  // ── School Identity ──
  'Basic Information': 'Enter your school\'s official name, complete address, phone number, email, principal\'s name, and year of establishment. This information appears on certificates, report cards, letterheads, and official communications.|Every certificate shows this as the school header. Fee receipts carry your school name and address. The parent portal displays your school\'s contact information.',
  'Academic Configuration': 'Set your board affiliation (CBSE, ICSE, State Board, IB), medium of instruction (English, Hindi, regional), and academic pattern (10+2, K-12). These are foundational academic identity details.|The exam module follows board-specific grading norms. Student profiles show the board. Certificates mention affiliation number. Transfer certificates include board details.',
  'Working Days': 'Set your weekly working pattern \u2014 which days is the school open? Most schools work Monday to Saturday or Monday to Friday. This is used for attendance percentage calculation and timetable generation.|Attendance calculates "present out of working days" using this pattern. The timetable generates schedules only for working days. Parents see the correct school calendar.',
  'Shift Configuration': 'If your school runs multiple shifts (Morning Shift: 7 AM - 12 PM, Afternoon Shift: 12:30 PM - 5:30 PM), configure them here with class assignments per shift. This is for schools that share infrastructure across two batches of students.|Teachers are assigned to shifts. Students see their shift timing. The timetable creates separate schedules per shift. Transport runs different routes per shift.',
  'Daycare & Extended Hours': 'If your school offers before-school or after-school care for children of working parents, configure the timings, capacity, and additional charges here.|Parents see daycare booking options. The Account Head collects daycare fees separately. Teachers on extended-hour duty see their assignments.',
  'System Configuration': 'Platform-level settings \u2014 notification channels (enable push, SMS, email, WhatsApp), default timezone, date format (DD/MM/YYYY or MM/DD/YYYY), session timeout (auto-logout after inactivity), and API access permissions.|All notifications follow your channel settings. Every user sees dates in your chosen format. Inactive sessions auto-logout for security.',

  // ── Onboarding Wizard ──
  'School Basic Info': 'First step of setup \u2014 enter your school name, type (day school, boarding, day-boarding), address, and primary contact. This is the foundation everything else builds on.|This information is used across all modules \u2014 on certificates, reports, communication, and every portal.',
  'Organisation Setup': 'Define your trust or management structure \u2014 single school, group of sister-concern schools under one trust, chain of schools with the same brand, or franchise model. This determines how schools share data and roles.|If you run multiple schools, this enables shared Trustee views across schools. Shared roles (like a common Account Head) are configured based on your org structure.',
  'Module Selection': 'Choose which ERP modules to activate based on your subscription plan. Unused modules are hidden from all dashboards to keep the interface clean. You can always enable more later.|Only selected modules appear in the sidebar navigation. Users see a focused interface without clutter. Your subscription determines which modules are available to select.',
  'Admin Account Creation': 'Create the first School Admin user who will handle day-to-day configuration and operations. This account gets full access to all school-level settings.|The School Admin you create here is the primary operator \u2014 they manage users, run reports, handle admissions, and configure modules. This is the most important account after SSA.',
  'Review & Launch': 'Final review of all your setup choices before the school goes live on the platform. Check school info, selected modules, and admin account. Once launched, all dashboards become accessible.|This is the point of no return \u2014 after launch, staff can start logging in and using the system. All modules you selected become active.',

  // ── Subscription ──
  'Current Plan': 'View your active subscription \u2014 plan name (Starter, Professional, Enterprise), billing period (monthly/yearly), renewal date, student limit, and included features. Know exactly what you are paying for and when it renews.|All module features are limited by your plan. If a feature is grayed out, it may require a plan upgrade. The school admin should review this periodically.',
  'Plan Comparison': 'See all available plans side by side \u2014 what each plan includes, how many students and staff it supports, storage limits, and pricing. Helps you decide whether to upgrade.|The school admin and Trustee review this when considering an upgrade. Features differ significantly between plans. Annual billing is usually cheaper than monthly.',
  'Usage Stats': 'Monitor your consumption against plan limits \u2014 active students, active staff, storage used, SMS sent this month, API calls made. Green means within limits, yellow means approaching, red means exceeded.|The school admin should check this monthly. Exceeding limits may degrade service or trigger upgrade prompts. Storage and SMS are the most common limits reached.',
  'Billing History': 'View past invoices and payment records \u2014 date, amount, plan, and payment status. Download invoices for accounting records.|The Account Head downloads invoices for record-keeping. Trustees can review subscription spending. Tax filing may require these invoices.',

  // ── Roles & Permissions ──
  'Permission Matrix': 'The core access control grid \u2014 for each role, toggle View (V), Create (C), Edit (E), Delete (D) permissions per module. For example, a Teacher might have V+C for Homework but only V for Fee Reports. This controls every action across the ERP.|If a user cannot see a button or access a page, check their role\'s permissions here. Every screen in the system checks this matrix before showing content.',
  'Custom Roles': 'Create roles specific to your school beyond the 15 built-in roles. For example, "Exam Coordinator" or "Sports Incharge" with specific permissions tailored to their duties.|Custom roles appear in the role assignment dropdown. The school admin creates these for special positions that don\'t fit standard roles.',
  'Role Hierarchy': 'Set parent-child relationships between roles \u2014 a child role automatically inherits all permissions of its parent plus any additional ones you add. For example, "Senior Teacher" inherits from "Teacher" but also gets exam creation access.|Inheritance simplifies permission management. When you update a parent role, all child roles automatically get those changes too.',
  'Clone Role': 'Duplicate an existing role as a starting point for a new one. For example, clone "Teacher" to create "Lab Instructor" and then add lab-specific permissions. Saves time compared to building from scratch.|The school admin uses this for quick role creation. The cloned role starts with identical permissions, which you can then customize.',
  'Assign Roles to Users': 'View all staff members and their current roles. Search, filter by role or department, and reassign roles as needed. This is where you connect people to their permissions.|The school admin manages all role assignments here. When a teacher takes on exam coordinator duties, reassign their role here. The change takes effect immediately.',
  'Bulk Operations': 'Assign a role to many users at once \u2014 for example, assign "Exam Invigilator" to 20 teachers before exam week, then remove it after exams. Much faster than editing one user at a time.|The school admin uses this before events or exam seasons. The exam coordinator can bulk-assign invigilation duties. Roles can be bulk-removed after the event.',
  'User Permission Override': 'Give or restrict specific permissions for individual users without changing their base role. For example, one teacher might need delete access to the homework module even though teachers normally cannot delete. This creates an exception for just that person.|The school admin creates overrides for special cases. The audit log tracks all overrides. Overrides appear highlighted on the user\'s permission view.',
  'Data Scope Configuration': 'Define what data each role can see \u2014 a class teacher sees only their class, a department HOD sees their entire department, a branch principal sees their branch, and the school admin sees everything. This controls data visibility boundaries.|Teachers cannot access data from other classes. HODs see aggregate department data. The Principal sees all-school data. This prevents unauthorized data access.',
  'Field-Level Access': 'Control visibility of sensitive fields per role \u2014 hide salary details from teachers, mask Aadhar numbers from non-HR staff, hide parent phone numbers from students. Sensitive fields can be fully hidden or partially masked (e.g., ****1234).|Teachers don\'t see salary columns in any reports. Only HR sees full Aadhar numbers. Privacy is maintained automatically based on your field-level settings.',
  'Default Dashboard Widgets': 'Pre-configure which widgets appear when each role logs in \u2014 teachers see attendance summary and upcoming classes, accountants see fee collection and pending receipts, principals see school-wide KPIs.|New users of each role see a relevant dashboard from day one. The school admin customizes this to match each role\'s daily needs.',
  'Permission Change Log': 'A complete audit trail of every role and permission change \u2014 who changed what, when, the before and after values. Tamper-proof and used for compliance audits.|The school admin reviews this to track recent changes. External auditors verify access control compliance using this log. Any unauthorized changes are immediately visible.',
  'Temporary Roles': 'Grant time-bound role elevations that automatically revert after expiry. For example, give a teacher "Exam Coordinator" access for 2 weeks during exams, and it auto-reverts to normal "Teacher" after the exam period.|The school admin sets the expiry date when granting temp roles. The system automatically reverts permissions \u2014 no manual cleanup needed. The audit log records the temporary grant.',
  'Compare Roles': 'View two roles side by side and see exactly where their permissions differ \u2014 highlighted in green (has permission) and red (does not). Useful for troubleshooting access issues or auditing role configurations.|The school admin uses this when a user reports they cannot access something \u2014 compare their role with one that can. Also useful during role audits.',

  // ── Backup & Export ──
  'Last Backup': 'Shows the most recent successful backup \u2014 date, time, file size, and status (success/failed). A quick health check to ensure your data is being backed up properly.|The school admin should check this regularly. If the last backup is old or failed, investigate immediately.',
  'Backup Schedule': 'Set automatic backup frequency \u2014 daily (recommended), weekly, or custom. Automated backups run without manual effort and ensure your data is always recoverable.|Daily backups mean you never lose more than 24 hours of data. The system handles this in the background. No action needed from the school admin after setup.',
  'Export Data': 'Download your school data in CSV, Excel, or JSON format \u2014 useful for board submissions, auditor requests, or migrating data to another system. Select which modules\' data to export.|The Account Head exports financial data for chartered accountants. The school admin exports student data for government submissions. HR exports staff data for compliance.',
  'Restore from Backup': 'Upload a backup file to restore your data to a previous state. This is the disaster recovery option \u2014 use it only if data has been accidentally deleted or corrupted. Requires verification before restore begins.|This is a critical safety net. The school admin uses this only in emergencies. Verification prevents accidental restores that could overwrite current data.',
  'Backup History': 'View a log of all past backups \u2014 date, size, type (automatic or manual), and status. Track backup consistency and spot failures early.|The school admin reviews this periodically to ensure backups are running consistently. Failed backups are flagged for investigation.',
};

export const FIELD_INFO: Record<string, string> = {
  // Fee Heads
  'Tuition Fee': 'The core monthly or annual teaching fee charged to every student. This is usually the largest fee component and covers classroom instruction costs.',
  'Admission Fee': 'One-time fee charged when a student joins the school for the first time. Not charged again in subsequent years unless re-admission occurs.',
  'Annual Charges': 'Yearly charges covering general school maintenance, infrastructure upkeep, and administrative costs. Billed once per academic year.',
  'Transport Fee': 'Monthly fee for students using school bus service. The amount may vary based on the route or stop distance if you chose distance-based transport pricing.',
  'Activity Fee': 'Covers extra-curricular activities \u2014 sports equipment, art supplies, club activities, and field trips. Usually charged quarterly or yearly.',
  'Lab Fee': 'For students who use science labs, computer labs, or other specialized facilities. Typically applicable from middle school onwards when lab work begins.',
  'Library Fee': 'Covers library access, new book purchases, and digital resources. Some schools include this in annual charges instead of charging separately.',
  'Exam Fee': 'Charged per exam cycle (term-wise or yearly) to cover question paper printing, answer sheet costs, invigilation, and result processing.',
  'Development Fund': 'One-time or annual contribution towards school expansion, new building construction, playground development, or infrastructure upgrades.',
  'Smart Class / IT Fee': 'For schools with digital classrooms, smart boards, or IT-enabled learning. Covers technology maintenance, software licenses, and internet costs.',
  'Uniform / Books': 'Enable this if your school collects uniform and textbook charges as part of the fee structure rather than having parents buy them separately.',
  'Hostel Fee': 'For boarding students \u2014 covers room, mess (meals), laundry, and other hostel services. Only relevant if your school has a hostel wing.',
  // Block rules
  'Block report card if fees overdue > 60 days': 'If enabled, the system will automatically prevent report card generation and download for students whose fees are overdue by more than 60 days. Parents will see a message asking them to clear dues before accessing results.',
  'Block TC generation if outstanding > 0': 'Transfer Certificate cannot be generated if the student has any unpaid fees. This ensures complete fee clearance before a student leaves the school.',
  'Block exam hall ticket if current term unpaid': 'Students with unpaid current-term fees will not receive exam hall tickets. Use with caution \u2014 this is a strong enforcement measure that directly affects students.',
  'Send auto-reminder before blocking': 'When enabled, the system sends a warning SMS and notification to parents a few days before any blocking action takes effect, giving them time to pay and avoid disruption.',
  // Concessions
  'Sibling Discount': 'Enable this if your school gives a fee discount when a parent has more than one child enrolled. The percentage you set will be automatically deducted from the second child onwards. Use the "Applies To" dropdown to choose which fee components get discounted — e.g., Tuition Only means only tuition is discounted, while All Components means every fee head gets the discount.',
  'Merit Scholarship': 'For students who score above a threshold in exams. Set the percentage discount and maximum amount. Requires principal approval before it reflects in fees.',
  'Staff Child': 'Full or partial fee waiver for children of school staff members. Enable this for automatic concession \u2014 the system detects staff-parent relationships.',
  'Economic Weaker (EWS)': 'For students admitted under the economically weaker section quota (RTE Act). Set the concession percentage as per government norms applicable to your state.',
  'Sports Quota': 'Discount for students selected under sports quota admission. Set percentage and cap amount. Typically requires documentation of sports achievements.',
  'SC/ST Scholarship': 'Fixed amount scholarship for SC/ST category students as per government scheme. This is usually a fixed rupee amount, not a percentage.',
  'Single Parent': 'Fee concession for students from single-parent families. Requires approval from the principal before applying to the student\'s account.',
  // Late Fee
  'Enable Late Fee': 'Turn on penalty charges for parents who pay after the due date. You can set the amount per day or per week, a grace period before penalties start, and a maximum cap so penalties stay reasonable.',
  // Payment modes
  'UPI': 'Allow parents to pay via UPI apps like Google Pay, PhonePe, or Paytm. This is the fastest online payment method with near-zero processing fees for the school.',
  'Net Banking': 'Allow direct bank transfers through internet banking. Takes 1-2 business days for reconciliation but is reliable for large payments.',
  'Credit Card': 'Accept Visa/Mastercard credit card payments. Higher processing fees (1-2%) but convenient for parents who want to use credit or EMI options.',
  'Debit Card': 'Accept bank debit/ATM card payments. Lower processing fees than credit cards and familiar to most parents.',
  'Cash': 'Accept cash payments at the school fee counter. Requires manual entry by the accountant or receptionist. Generates a paper receipt.',
  'Cheque': 'Accept bank cheques. Requires manual reconciliation after cheque clearance (2-3 working days). Risk of cheque bounce.',
  'DD/NEFT': 'Accept demand drafts or bank wire transfers (NEFT/RTGS/IMPS). Used for large payments or when parents bank from a different city.',
};
