import {
  Home, Banknote, GraduationCap, Briefcase, Bus, ClipboardCheck, FileText,
  MessageSquare, Calendar, Clock, Shield, Award, Upload, ShieldCheck, Headphones,
  Download, BookOpen, Users, Lock, Key,
  UtensilsCrossed, Building, Package, Notebook, UserPlus, CreditCard,
  UserCircle, BarChart3, FileBarChart, Plug, Palette, School, Globe,
  Database, Smartphone, MessageSquareText, MonitorPlay
} from 'lucide-react';

export const modules = [
  { id: 'onboarding-wizard', label: 'Onboarding Wizard', icon: School },
  { id: 'dashboard', label: 'Dashboard', icon: Home },
  { id: 'subscription-mgmt', label: 'Subscriptions', icon: CreditCard },
  { id: 'fee-config', label: 'Fee Configuration', icon: Banknote },
  { id: 'academic-config', label: 'Academic Config', icon: GraduationCap },
  { id: 'hr-config', label: 'HR & Payroll', icon: Briefcase },
  { id: 'transport-config', label: 'Transport', icon: Bus },
  { id: 'attendance-config', label: 'Attendance', icon: ClipboardCheck },
  { id: 'exam-config', label: 'Exams & Grading', icon: FileText },
  { id: 'communication-config', label: 'Communication', icon: MessageSquare },
  { id: 'timetable-config', label: 'Timetable & Bell', icon: Calendar },
  { id: 'leave-config', label: 'Leave Policy', icon: Clock },
  { id: 'visitor-config', label: 'Visitor Rules', icon: Shield },
  { id: 'certificate-config', label: 'Certificates', icon: Award },
  { id: 'library-config', label: 'Library', icon: BookOpen },
  { id: 'canteen-config', label: 'Canteen / Meal', icon: UtensilsCrossed },
  { id: 'hostel-config', label: 'Hostel', icon: Building },
  { id: 'inventory-config', label: 'Inventory & Assets', icon: Package },
  { id: 'compliance-config', label: 'Compliance & Quality', icon: ShieldCheck },
  { id: 'role-management', label: 'Roles & Permissions', icon: Key },
  { id: 'homework-config', label: 'Homework & Assignment', icon: Notebook },
  { id: 'enquiry-config', label: 'Enquiry & Admission', icon: UserPlus },
  { id: 'payment-config', label: 'Online Payment', icon: CreditCard },
  { id: 'data-migration', label: 'Data Migration', icon: Upload },
  { id: 'critical-locks', label: 'Critical Locks', icon: Lock },
  { id: 'audit-log', label: 'Audit Log', icon: ShieldCheck },
  { id: 'backup-export', label: 'Backup & Export', icon: Download },
  { id: 'parent-portal-config', label: 'Parent Portal', icon: UserCircle },
  { id: 'student-portal-config', label: 'Student Portal', icon: Users },
  { id: 'alumni-config', label: 'Alumni', icon: Globe },
  { id: 'analytics-config', label: 'Analytics & BI', icon: BarChart3 },
  { id: 'report-engine-config', label: 'Report Engine', icon: FileBarChart },
  { id: 'api-integration-config', label: 'API & Integrations', icon: Plug },
  { id: 'branding-config', label: 'Branding & White-label', icon: Palette },
  { id: 'school-identity-config', label: 'School Identity', icon: School },
  { id: 'data-privacy-config', label: 'Data Privacy', icon: Shield },
  { id: 'demo-data-seeder', label: 'Demo Data Seeder', icon: Database },
  { id: 'mobile-app-config', label: 'Mobile App', icon: Smartphone },
  { id: 'remark-bank-config', label: 'Remark Bank', icon: MessageSquareText },
  { id: 'lms-config', label: 'LMS / E-Learning', icon: MonitorPlay },
  { id: 'your-inputs', label: 'Your Inputs', icon: ClipboardCheck },
  { id: 'support', label: 'Support', icon: Headphones },
];
